#!/bin/sh
set -e

case "$1" in
    purge)
        # Remove irgsh user and group on purge
        if getent passwd irgsh >/dev/null; then
            deluser --quiet irgsh || true
        fi

        if getent group irgsh >/dev/null; then
            delgroup --quiet irgsh || true
        fi

        # Remove log files and working directory on purge
        rm -rf /var/log/irgsh
        rm -rf /var/lib/irgsh
        rm -rf /etc/irgsh
        ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'irgsh-builder.service' 'irgsh-chief.service' 'irgsh-iso.service' 'irgsh-repo.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
