ARG DEBIAN_SUITE=bookworm
FROM debian:${DEBIAN_SUITE}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    wget \
    git \
    build-essential \
    gpg \
    pbuilder \
    debootstrap \
    devscripts \
    curl \
    reprepro \
    dh-make \
    sudo \
    lsb-release \
    docker.io \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ARG GO_VERSION=1.13.15
RUN wget https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz && \
    rm go${GO_VERSION}.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin

WORKDIR /app

EXPOSE 8080 8081 8082
