package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"os"
	"strings"

	"github.com/blankon/irgsh-go/pkg/systemutil"
	"github.com/google/uuid"
)

func InitBase() (err error) {
	logPath := irgshConfig.Builder.Workdir
	logPath += "/irgsh-builder-init-base-" + uuid.New().String() + ".log"
	go systemutil.StreamLog(logPath)

	cmdStr := "lsb_release -a | grep Distributor | cut -d ':' -f 2 | awk '{print $1=$1;1}'"
	distribution, _ := systemutil.CmdExec(
		cmdStr,
		"",
		logPath,
	)

	// TODO base.tgz file name should be based on distribution code name
	fmt.Println("WARNING: This subcommand need to be run under root or sudo.")
	x, _ := json.Marshal(irgshConfig.Builder)
	fmt.Println(string(x))

	fmt.Println("Installing and preparing pbuilder and friends...")

	cmdStr = "apt-get update && apt-get install -y pbuilder debootstrap devscripts equivs"
	_, err = systemutil.CmdExec(
		cmdStr,
		"Preparing pbuilder and it's dependencies",
		logPath,
	)
	if err != nil {
		fmt.Printf("error: %v\n", err)
		return
	}

	cmdStr = "rm /var/cache/pbuilder/base*"
	_, _ = systemutil.CmdExec(
		cmdStr,
		"",
		logPath,
	)

	// Create /root/.pbuilderrc with builder config
	fmt.Println("Creating /root/.pbuilderrc...")
	pbuilderrcContent := fmt.Sprintf(`# Generated by irgsh-builder init
MIRRORSITE="%s"
DISTRIBUTION="%s"
BASETGZ="/var/cache/pbuilder/base.tgz"
BUILDRESULT="/var/cache/pbuilder/result/"
APTCACHE="/var/cache/pbuilder/aptcache/"
BUILDPLACE="/var/cache/pbuilder/build/"
USENETWORK=yes
`, irgshConfig.Builder.UpstreamDistUrl, irgshConfig.Builder.UpstreamDistCodename)

	err = ioutil.WriteFile("/root/.pbuilderrc", []byte(pbuilderrcContent), 0644)
	if err != nil {
		fmt.Printf("error creating /root/.pbuilderrc: %v\n", err)
		return
	}
	fmt.Println("Created /root/.pbuilderrc with MIRRORSITE=" + irgshConfig.Builder.UpstreamDistUrl + " and DISTRIBUTION=" + irgshConfig.Builder.UpstreamDistCodename)

	cmdStr = "pbuilder create --debootstrapopts --variant=buildd"
	if strings.Contains(irgshConfig.Builder.UpstreamDistUrl, "debian") && (strings.Contains(distribution, "Ubuntu") ||
		strings.Contains(distribution, "Pop")) {
		_, err = systemutil.CmdExec(
			"apt-get update && apt-get -y install debian-archive-keyring",
			"Creating pbuilder base.tgz",
			logPath,
		)
		if err != nil {
			fmt.Printf("error: %v\n", err)
			return
		}
		cmdStr = "pbuilder create --distribution " + irgshConfig.Builder.UpstreamDistCodename + " --mirror " + irgshConfig.Builder.UpstreamDistUrl + " --debootstrapopts \"--keyring=/usr/share/keyrings/debian-archive-keyring.gpg\""
	}
	_, err = systemutil.CmdExec(
		cmdStr,
		"Creating pbuilder base.tgz",
		logPath,
	)
	if err != nil {
		fmt.Printf("error: %v\n", err)
		return
	}

	cmdStr = "pbuilder update"
	_, err = systemutil.CmdExec(
		cmdStr,
		"Updating base.tgz",
		logPath,
	)
	if err != nil {
		fmt.Printf("error: %v\n", err)
		return
	}

	cmdStr = "chmod a+rw /var/cache/pbuilder/base*"
	_, err = systemutil.CmdExec(
		cmdStr,
		"Fixing permission for /var/cache/pbuilder/base*",
		logPath,
	)
	if err != nil {
		fmt.Printf("error: %v\n", err)
		return
	}

	if irgshConfig.IsDev {
		cwd, _ := os.Getwd()
		tmpDir := cwd + "/tmp/"
		cmdStr = "chmod -vR 777 " + tmpDir
		_, err = systemutil.CmdExec(
			cmdStr,
			"Fixing permission for "+tmpDir,
			logPath,
		)
		if err != nil {
			fmt.Printf("error: %v\n", err)
			return
		}
	}

	fmt.Println("Done.")

	return
}

func UpdateBase() (err error) {
	fmt.Println("WARNING: This subcommand need to be run under root or sudo.")
	logPath := "/tmp/irgsh-builder-update-base-" + uuid.New().String() + ".log"
	go systemutil.StreamLog(logPath)

	fmt.Println("Updating base.tgz...")
	cmdStr := "sudo pbuilder update"
	_, err = systemutil.CmdExec(
		cmdStr,
		"Updating base.tgz",
		logPath,
	)
	if err != nil {
		fmt.Printf("error: %v\n", err)
		return
	}

	fmt.Println("Done.")

	return
}

// pbockerDockerfile is the image the packages are actually built in: a
// pbuilder inside a container. Everything it needs is written next to it as a
// real file and COPYied in, rather than assembled from a chain of echoes.
const pbockerDockerfile = `FROM debian:latest
RUN apt-get update && apt-get -y install pbuilder ca-certificates
COPY pbuilderrc /root/.pbuilderrc
COPY base.tgz /var/cache/pbuilder/
COPY hooks/ /var/cache/pbuilder/hooks/
COPY build.sh /build.sh
RUN chmod a+x /build.sh /var/cache/pbuilder/hooks/* && \
    cp /etc/ssl/certs/ca-certificates.crt /var/cache/pbuilder/hooks/ca-certificates.crt
`

// resolvConfHook runs inside the build chroot before the build dependencies
// are installed. pbuilder copies the container's /etc/resolv.conf into the
// chroot, and that resolver is often a single forwarder (Docker's embedded
// 127.0.0.11) whose upstream drops queries under load - which surfaces much
// later as "Could not resolve host" from apt, or from whatever the package's
// own build system fetches. Keep the inherited resolvers, append known-good
// public ones, and make the resolver itself retry instead of giving up on the
// first timeout.
const resolvConfHookTemplate = `#!/bin/bash
# Generated by irgsh-builder init. Do not edit; regenerate with irgsh-builder init.
set -u

fallbacks="%s"
tmp=$(mktemp)
inherited=$(mktemp)

# 127.0.0.53 is the systemd-resolved stub; nothing listens on it in here.
grep -E '^[[:space:]]*nameserver[[:space:]]' /etc/resolv.conf 2>/dev/null \
    | grep -vE 'nameserver[[:space:]]+127\.0\.0\.53' > "$inherited" || true

# glibc only honours the first three nameservers, so keep only as many
# inherited resolvers as still leave room for the fallbacks - otherwise a host
# that already lists three would push them straight back out of the file.
keep=$(( 3 - $(echo $fallbacks | wc -w) ))
[ "$keep" -lt 0 ] && keep=0
head -n "$keep" "$inherited" > "$tmp"

for ns in $fallbacks; do
    grep -qE "^[[:space:]]*nameserver[[:space:]]+${ns}([[:space:]]|$)" "$tmp" || echo "nameserver ${ns}" >> "$tmp"
done

head -n 3 "$tmp" > /etc/resolv.conf
echo 'options timeout:2 attempts:3 rotate' >> /etc/resolv.conf
rm -f "$tmp" "$inherited"

echo "irgsh: build chroot resolv.conf:"
cat /etc/resolv.conf
`

// caCertsHook repairs the chroot's TLS trust store before the build runs.
// A buildd-variant chroot is minimal, and its ca-certificates bundle is
// routinely absent, empty, or left unregenerated when the package arrives as
// somebody's build dependency. Anything fetching over HTTPS during the build
// (cargo, npm, go) then fails with curl's "[77] Problem with the SSL CA cert",
// which reads like a network fault but survives every retry.
const caCertsHook = `#!/bin/bash
# Generated by irgsh-builder init. Do not edit; regenerate with irgsh-builder init.
set -u

bundle=/etc/ssl/certs/ca-certificates.crt

usable() {
    [ -s "$bundle" ] && grep -q 'BEGIN CERTIFICATE' "$bundle"
}

if ! dpkg-query -W -f='${Status}' ca-certificates 2>/dev/null | grep -q 'ok installed'; then
    echo "irgsh: installing ca-certificates in the build chroot"
    apt-get update -qq || true
    apt-get install -y --no-install-recommends ca-certificates || true
fi

if ! usable; then
    echo "irgsh: regenerating $bundle"
    rm -f "$bundle"
    update-ca-certificates --fresh || true
fi

# Last resort: the image's own bundle, staged next to this hook (the hook dir
# is bind-mounted into the chroot, so it is readable from in here). This is
# what makes the build independent of whatever state ca-certificates is in
# inside the chroot.
if ! usable; then
    staged="$(dirname "$0")/ca-certificates.crt"
    if [ -s "$staged" ]; then
        echo "irgsh: installing the pbocker image's CA bundle into the chroot"
        mkdir -p "$(dirname "$bundle")"
        rm -f "$bundle"
        cp "$staged" "$bundle"
        chmod 0644 "$bundle"
    fi
fi

if usable; then
    echo "irgsh: $bundle carries $(grep -c 'BEGIN CERTIFICATE' "$bundle") certificate(s)"
else
    echo "irgsh: WARNING: $bundle is still unusable; HTTPS downloads during the build will fail"
fi
`

// pbockerBuildScript builds the .dsc mounted at /tmp/build and copies the
// results back out. A build that failed on a transient network or DNS error
// is retried: those failures say nothing about the package, and a maintainer
// re-submitting by hand is the only alternative.
const pbockerBuildScript = `#!/bin/bash
# Generated by irgsh-builder init. Do not edit; regenerate with irgsh-builder init.
set -u

attempts=${BUILD_ATTEMPTS:-3}
log=$(mktemp)

transient() {
    grep -qEi 'Could not resolve|Temporary failure resolving|Temporary failure in name resolution|Failed to fetch|Connection (timed out|failed)|Network is unreachable|Cannot initiate the connection|Unable to connect to' "$log"
}

attempt=1
while true; do
    : > "$log"
    pbuilder --build /tmp/build/*.dsc 2>&1 | tee -a "$log"
    rc=${PIPESTATUS[0]}
    [ "$rc" -eq 0 ] && break
    if [ "$attempt" -ge "$attempts" ] || ! transient; then
        echo "irgsh: build failed (exit ${rc}) after ${attempt} attempt(s)"
        rm -f "$log"
        exit "$rc"
    fi
    echo "irgsh: transient network failure, retrying build ($((attempt + 1))/${attempts}) in $((attempt * 15))s..."
    sleep $((attempt * 15))
    attempt=$((attempt + 1))
done
rm -f "$log"

cp -vR /var/cache/pbuilder/result/*.deb /tmp/build/
cp -vR /var/cache/pbuilder/result/*.buildinfo /tmp/build/ || true
`

// writePbockerContext writes the docker build context for the pbocker image.
func writePbockerContext(dir string) (err error) {
	if err = os.MkdirAll(dir+"/hooks", 0755); err != nil {
		return
	}

	pbuilderrc := fmt.Sprintf(`# Generated by irgsh-builder init
MIRRORSITE=%s
BUILDUSERID=0
BUILDUSERNAME=root
USENETWORK=yes
HOOKDIR=/var/cache/pbuilder/hooks
`, irgshConfig.Builder.UpstreamDistUrl)

	files := map[string]struct {
		content string
		mode    os.FileMode
	}{
		dir + "/Dockerfile": {pbockerDockerfile, 0644},
		dir + "/pbuilderrc": {pbuilderrc, 0644},
		dir + "/build.sh":   {pbockerBuildScript, 0755},
		// D hooks run inside the chroot after apt is set up and before the
		// build dependencies are installed, so the fixed resolv.conf covers
		// both the dependency install and the build itself.
		dir + "/hooks/D10resolvconf": {
			fmt.Sprintf(resolvConfHookTemplate, strings.Join(irgshConfig.Builder.Resolvers(), " ")),
			0755,
		},
		dir + "/hooks/D20cacerts": {caCertsHook, 0755},
	}
	for path, f := range files {
		if err = ioutil.WriteFile(path, []byte(f.content), f.mode); err != nil {
			return
		}
	}
	return
}

func InitBuilder() (err error) {
	logPath := irgshConfig.Builder.Workdir
	logPath += "/irgsh-builder-init-" + uuid.New().String() + ".log"
	go systemutil.StreamLog(logPath)

	fmt.Println("Preparing containerized pbuilder...")

	pbockerDir := irgshConfig.Builder.Workdir + "/pbocker"
	cmdStr := `mkdir -p ` + pbockerDir + ` && \
    cp /var/cache/pbuilder/base.tgz ` + pbockerDir + `/base.tgz`
	_, err = systemutil.CmdExec(
		cmdStr,
		"Copying base.tgz",
		logPath,
	)
	if err != nil {
		fmt.Printf("error: %v\n", err)
		return
	}

	if err = writePbockerContext(pbockerDir); err != nil {
		fmt.Printf("error preparing pbocker build context: %v\n", err)
		return
	}
	fmt.Println("Wrote pbocker build context to " + pbockerDir +
		" (fallback DNS: " + strings.Join(irgshConfig.Builder.Resolvers(), ", ") + ")")

	cmdStr = `cd ` + pbockerDir + ` && docker build --no-cache -t pbocker .`
	_, err = systemutil.CmdExec(
		cmdStr,
		"Building pbocker docker image",
		logPath,
	)
	if err != nil {
		fmt.Printf("error: %v\n", err)
		return
	}

	fmt.Println("Done.")

	return
}
