#!/usr/bin/env bash
rm -f irgsh-go/
rm -f irgsh-go/etc/
rm -f irgsh-go/etc/irgsh/
rm -f irgsh-go/etc/irgsh/config.yaml
rm -f irgsh-go/lib/
rm -f irgsh-go/lib/systemd/
rm -f irgsh-go/lib/systemd/system/
rm -f irgsh-go/lib/systemd/system/irgsh-builder.service
rm -f irgsh-go/lib/systemd/system/irgsh-chief.service
rm -f irgsh-go/lib/systemd/system/irgsh-repo.service
rm -f irgsh-go/lib/systemd/system/irgsh-iso.service
rm -f irgsh-go/usr/
rm -f irgsh-go/usr/share/
rm -f irgsh-go/usr/share/irgsh/
rm -f irgsh-go/usr/share/irgsh/reprepro-template/
rm -f irgsh-go/usr/share/irgsh/reprepro-template/conf/
rm -f irgsh-go/usr/share/irgsh/reprepro-template/conf/blacklist.pkg
rm -f irgsh-go/usr/share/irgsh/reprepro-template/conf/tiffany.py
rm -f irgsh-go/usr/share/irgsh/reprepro-template/conf/changelogs.sh
rm -f irgsh-go/usr/share/irgsh/reprepro-template/conf/distributions.orig
rm -f irgsh-go/usr/share/irgsh/reprepro-template/conf/options.orig
rm -f irgsh-go/usr/share/irgsh/reprepro-template/conf/updates.orig
rm -f irgsh-go/usr/bin/
rm -f irgsh-go/usr/bin/irgsh-cli
rm -f irgsh-go/usr/bin/irgsh-builder
rm -f irgsh-go/usr/bin/irgsh-chief
rm -f irgsh-go/usr/bin/irgsh-repo
