[package]
name = "cli-rust"
version = "0.1.0"
authors = ["BlankOn Developer <blankon-dev@googlegroups.com>","Herpiko Dwi Aguno <herpiko@aguno.xyz>"]
edition = "2018"

[dependencies]
clap = "2.26.0"
dirs = "1.0.5"
reqwest = "0.9.15"
serde_json = "1.0.39"
