name: Deployment Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        sudo apt update && sudo apt install -y gpg pbuilder debootstrap devscripts python-apt reprepro make
        curl -O https://storage.googleapis.com/golang/go1.13.14.linux-amd64.tar.gz
        tar -xf go1.13.14.linux-amd64.tar.gz
        sudo mv go /usr/local
        make release
        cp irgsh-go/usr/bin/irgsh-cli target/irgsh-cli

    - uses: actions/upload-artifact@master
      with:
        name: release
        path: target/

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args:
        - target/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to rani
      env:
        HOST: ${{secrets.RANI_HOSTNAME}}
        KEY: ${{secrets.JIN_IPRIT}}
      run: |
        curl --header "Content-Type: application/json" --request POST --data '{"name":"irgsh","token": "$KEY"}' https://$HOST
