name: master

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        sudo apt update && sudo apt install -y gpg pbuilder debootstrap devscripts python-apt reprepro make
        curl -O https://storage.googleapis.com/golang/go1.11.2.linux-amd64.tar.gz
        tar -xvf go1.11.2.linux-amd64.tar.gz
        sudo mv go /usr/local
        make build
        mkdir -p irgsh/bin
        cp ./bin/irgsh-builder binary/bin/
        cp ./bin/irgsh-iso binary/bin/
        cp ./bin/irgsh-cli binary/bin/
        cp ./bin/irgsh-chief binary/bin/
        cp ./bin/irgsh-repo binary/bin/

    - uses: actions/upload-artifact@master
      with:
        name: irgsh-go
        path: binary/bin
