name: master

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        sudo apt update && sudo apt install -y gpg pbuilder debootstrap devscripts python-apt reprepro make
        curl -O https://storage.googleapis.com/golang/go1.11.2.linux-amd64.tar.gz
        tar -xvf go1.11.2.linux-amd64.tar.gz
        sudo mv go /usr/local
        make build
        mkdir -p x64-release/bin
        cp ./bin/irgsh-builder x64-release/bin/
        cp ./bin/irgsh-iso x64-release/bin/
        cp ./bin/irgsh-cli x64-release/bin/
        cp ./bin/irgsh-chief x64-release/bin/
        cp ./bin/irgsh-repo x64-release/bin/

    - uses: actions/upload-artifact@master
      with:
        name: irgsh-go
        path: x64-release/bin
